import type { Metadata } from "next";
import { Gelasio } from "next/font/google";
import SmoothScrolling from "@/components/SmoothScrolling";

import "@/styles/globals.scss";


const gelasio = Gelasio({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// const roboto = Roboto({
//   weight: ["100", "300", "400", "500", "700"],
//   style: ["normal", "italic"],
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning className={`${gelasio.className} antialiased`}
      >
        <SmoothScrolling>
          <main>
            {children}
          </main>
        </SmoothScrolling>
      </body>
    </html>
  );
}
